name: Comment
description: Provide generic feedback about using Matrix at WordPress.org

labels: ["Feature: Discussion", "Matrix","community.wordpress.org"]
projects: "WordPress/150"

body:
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - Operating System: [e.g., Windows, macOS, Linux]
        - Browser: [e.g., Chrome, Firefox]
        - Client: [e.g., Element Web, Chatrix, a URL like matrix.wordpress.net]
        - Version: [e.g., 1.0.0, latest commit hash]

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      placeholder: Describe what you expected to happen...

  ## A clear and concise description of what actually happened.
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      placeholder: Describe what actually happened...
      
  ## Screenshots or screen recordings if applicable.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: Drag and drop or paste screenshots here...

  ## Any additional information or context about the bug.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: Add any additional information here...
